### ISSUE TITLE
permitir que processo BPM reprove uma proposta

### ISSUE THREAD

**Issue by AndreiBarroso** [Ensino-FAB/workspace-ensino#20]

**Comment by aguiardafa** [comment]
Ajuste no processo de tramitação de Propostas de Conclusões de Curso (BPM), para permitir finalizar o processo com a reprovação da Proposta;
Ou seja, na etapa de análise o operador poderá devolver a Proposta para correção, poderá aprovar a Proposta e ela gerar conclusões, e poderá ser reprovada e finalizada a tramitação.
